let tracksDatabase = [
  {
    "id": "rec3k4Mu0bNBE1gqd",
    "createdTime": "2024-02-10T07:58:21.000Z",
    "fields": {
      "Name": "Conic Sections",
      "Item ID": "65c7256123f9a2118f7e4e4c",
      "Slug": "conic-sections",
      "Nodes": [
        "recyNMwN5vBWDm1Wn",
        "recEWWXTJOBhKVnth",
        "recPm4hICXUAiaPSJ",
        "recn9dZIBIKhdNycB",
        "recKVtNXqxjiIDU3l",
        "recZBXi5i3xsNYBZS",
        "recDvaucwU6gdAiyh",
        "rec2tENApTjs7PjKp",
        "recvmRsviSlXKtk6G",
        "recUlGLyP6pmIkkY6",
        "reciteWgQ8kaiecEl",
        "recePfQ2Zp0nxNJjV",
        "recIPXTkMNohMxZQC",
        "recc8MzQG5zlZ7VBI"
      ],
      "Version": 1,
      "Description": "This track focuses on brief overview of the conic sections - parabola, ellipse, and hyperbola.\n"
    }
  },
  {
    "id": "recAJPDyTiMpa4xtQ",
    "createdTime": "2024-01-09T09:31:33.000Z",
    "fields": {
      "Name": "Classical Structural Analysis",
      "Item ID": "659d0d8ed2b1cf5a93f24be3",
      "Slug": "classical-structural-analysis",
      "Nodes": [
        "recFnOVAj5Jzh7pu9",
        "rec4OtOiF4IWFYL4o",
        "rec0gOJox3OGpXzTF",
        "rec3qK3cct95CsuX1",
        "rec8JA1707i7en06Q",
        "recr13UJa8DvT8mkZ",
        "reccwD9HPgLQD9q00",
        "recGeLLEBy3zPr8CT",
        "recysej3plsOBDHsX",
        "rec8cAnazv7cLsrNb",
        "recw53t2JbZvVnpJZ",
        "recYlWMz3XqsTVXWD",
        "recIaGLwn69Un34Uy",
        "rec15nZj71Qa6UvVa",
        "recLtbOqubkfRmjjH",
        "recdaMdpYKA6qm89n",
        "recpz2spSbolENrhk",
        "rec7FXxf1tOHktxeO",
        "recUrTjPKnSBVvMXk",
        "recVnleU1MC7YARxo",
        "recdKyaNWpwnirW8Y",
        "recndOqYjMpWQyFTD",
        "recEOlxaAbIukNhqv",
        "recuKVUODsUQHUCzb",
        "recz9jOvPr145DpXI",
        "rec4pTshq7HgummR1",
        "recSR2D2shTMeNfqk",
        "recevAHgPmwv7rNm1",
        "rechNtjUxTVcHmFMT",
        "recHxOlq9EBE5CDtJ",
        "reciaylm9cHjPiUUR",
        "recFPtN5M56B7X2eV",
        "recTkoGgOOxJa9JTg",
        "recd3lmW0jVcxyClW",
        "recPaKwgSjDKKs2OK",
        "rec8nAtR4JCCghVX4",
        "recvcw1W8UJKVKjuy",
        "recxN8xumxCdhF7KM",
        "recdI5WZVpXOpLZKE",
        "recNGXnNcJOyCi834",
        "rec6yl9U1JMzrVrqK",
        "recnUYsEBO0K7Kb6B",
        "recNE73jnGO9LlvTZ",
        "recEBLgy4lj1HXON1",
        "recQ8mRjl7tDRWGRh",
        "rechcyyNzsaK6dp6w",
        "rec01WMpgA0BKWqtG",
        "recMh3cbrBUJbbNgL",
        "recauW5UJpuPd7MN1",
        "rec3UxyMlImgxTUxt",
        "recBsDgA57xdOlHPN",
        "rec1TacTSSrRdvKIp",
        "recsjEmwRv84joHlf",
        "rec46n0JQr6qHOLqN",
        "rec14W03Sx9TmmYag",
        "recInVP5uHEWCbIWg",
        "recMbQNWYKLGXnoep",
        "rech2jAP8V7MaHb60",
        "recq5RCfsRMz25zsB",
        "recLuBaVQKYdYaJwV",
        "recxvySqJ68aNUY2C",
        "recZvOQvxQFPfgG3c",
        "recCNelNosYyMEANO",
        "recLWJnaiwLjqzACi",
        "recjI4H7282MXY9EZ",
        "recuM4u6lOkBwfZ4n",
        "recS8RKz4iogHQVlC",
        "recXxLMdboDGNm2QJ",
        "recTZiWX515TCWTmK",
        "rectJopYHKsq6uzf9",
        "rec6GLYhVt6GlyZlg",
        "recVluKkdGdtSDwKw",
        "rec9Opg7uUaNVG6f3",
        "recZqdDlL0J4JQ7ST",
        "recHfdFYypTba3Sv9",
        "recnVObn1zC9Her1c",
        "recqcQbwd6FJSb7jg",
        "recb85Va9yQs1SMFx",
        "recf15vYZV9wehFAx",
        "rectnuMdhNyazti7w",
        "recQPHhAYFAW3WBR4",
        "recxFJi5DX8EV7WWr",
        "recLZlhqda5wasEh1",
        "recSfMcrxqCdo9mLX",
        "recWlH8DjqbUtsx6F",
        "recOkEydoI3HcE9lx",
        "recibzkYaCLAoySfv",
        "recpHF8Cg89Vuh9a7",
        "rec5cuqItzIZs9N14",
        "reciCW7goqgOc0WHu"
      ],
      "Version": 1,
      "Description": "This track focuses on structural analysis using the classical approach with emphasis on concepts and methods such as: static determinate analysis of trusses, beams, and frames (stability, determinacy, reactions, internal forces, and deflection).\n"
    }
  },
  {
    "id": "recAfXEx9a47fAAAt",
    "createdTime": "2024-02-10T07:58:21.000Z",
    "fields": {
      "Name": "Differential Equations",
      "Item ID": "65c7258e17fcb5339e1d8e20",
      "Slug": "differential-equations",
      "Nodes": [
        "recTJTOlag5moRMAz",
        "recMwIVQMeZFV0Uy2",
        "rec6pYABydUtZPdtR",
        "recGk3QAV81FDz69h",
        "recQYLiwHfnOWCLpg",
        "rec3R5fKLUaXBO1Nb",
        "recsupTLt6yVHzmBM",
        "recWTNUQ6umrLeycN",
        "recQosmhQmV7zobeU",
        "recN1mK5Gf7AbmKBJ",
        "recVwQ4rWBnxzAFx8",
        "recLTb1H0znUGbrn2",
        "recvbQDhEVGD8aALx",
        "recgTlwnFSEZN8AVT",
        "recaJWFPui8Z5KaAC",
        "recuFh4sciHUZfrsh"
      ],
      "Version": 1,
      "Description": "This tracks focuses on a elementary overview of Differential Equations. Topics include basic definition, the different types of solutions, analytical methods, and some applications.\n"
    }
  },
  {
    "id": "recU6E7VRWfAQSm2o",
    "createdTime": "2024-01-09T05:19:20.000Z",
    "fields": {
      "Name": "Structural Modeling",
      "Item ID": "659cd4609b3017ddad0e27ad",
      "Slug": "structural-modeling",
      "Nodes": [
        "recES3gDB32VysGf1",
        "recgmK7kf3ke7ufdP",
        "rec0bh6y3ggaHIUJb",
        "recItbtoinRGHKqsJ",
        "recOsTQ2yn3iMO2kB",
        "recaC4AWiJgH1bDxu",
        "recdyw7GvBujike7k",
        "rec2sOH5hibVRSuBg",
        "recVFJZLyOwTQZQ7C",
        "reczrDKRD2XRwFxl2",
        "recoeDE0cGtWl0Kn9",
        "recdrFdqlGhCJ5CmQ",
        "recvMpeeKHQfw2uks",
        "rech7VxE231YP6TMl",
        "rectwk8Mn2Lgir8Yk",
        "recYFslKbqPl33Lrl",
        "recNDXO7pnC8Tun42",
        "recZ7eQYVAUUX6thM",
        "recpMuLYQFEXmfUGu",
        "recKJ7ITqCP4NORD0",
        "recoi7UJD8XAGhhgg",
        "reconRJ15nWVA3rzT"
      ],
      "Version": 1,
      "Description": "This track focuses on structural modeling which is about creating the skeleton frame of the structure itself. We discuss structural model, analytical model, components (joints, members, and supports), and some basic structural units (trusses, beams, and frames).\n"
    }
  },
  {
    "id": "recjrMbu7V7jM6iPd",
    "createdTime": "2024-02-10T07:58:21.000Z",
    "fields": {
      "Name": "Applications of Definite Integral",
      "Item ID": "65c725833673a934742cd8b8",
      "Slug": "applications-of-definite-integral",
      "Nodes": [
        "recr3u3RSVdoqFNrl",
        "recNJYE5Kg4zCOuJK",
        "recn3NcEV7JbR20vi",
        "recXg3q5obV8OUNPr",
        "recOsB7NfKvuPlUJe",
        "rec4nqImwRDdSYoJ2",
        "recIDCVNtjegqyrT4",
        "recQ6aDy2wQCGDlE6",
        "reciBOyzrXyNtazrD",
        "recRW0BJbibJC5cgm"
      ],
      "Version": 1,
      "Description": "This track focuses on application of the definite integral: finding the arc of a curve, solving area between curves, and finding volumes of solid objects.\n"
    }
  },
  {
    "id": "recvAGeu6W2P2F8dD",
    "createdTime": "2024-02-10T07:58:21.000Z",
    "fields": {
      "Name": "Mathematical Functions",
      "Item ID": "65c725a0de35e6f5002d09bf",
      "Slug": "mathematical-functions",
      "Nodes": [
        "recxvW2R2r5g491G9",
        "rec45eAk7qieXpK0Q",
        "recOzjBpYXIUHuiNE",
        "recz0XAKWnXf3rqPr",
        "receR3QWJziq79jYm",
        "recLxnnuxYuXOjDAa",
        "recE5Id3SkwtdJ03L",
        "recg7ioFXWNMFHYjJ",
        "rec3A2czYMVYOhblZ",
        "recDNNRS4bqMf5vRs",
        "rechUEV8mTQqcSxjj",
        "rechwpC1c0dSB5LhX",
        "recnUvDePj7m9c4Z5",
        "recu1GZ7Err23mN86"
      ],
      "Version": 1,
      "Description": "This track focuses on a basic overview of mathematical functions - introduction, construction, and types.\n"
    }
  },
  {
    "id": "recwMquYsvF088qFE",
    "createdTime": "2024-01-09T09:31:33.000Z",
    "fields": {
      "Name": "Structural Loads",
      "Item ID": "659d0d7072e24f674ffd03ad",
      "Slug": "structural-loads",
      "Nodes": [
        "recSMcfXIExrOts9f",
        "recUsiVVPvF5i3f6S",
        "recaKCKG3sfNHqvxB",
        "recabrxf8eUisN21V",
        "recfoTRCAbGQhcT6o",
        "recZLwB6pRypXoEqn"
      ],
      "Version": 1,
      "Description": "This track focuses on basic overview of structural loads - definition, origin, types of loads, and properties.\n"
    }
  },
  {
    "id": "recyT5SjHhEQq1Zvs",
    "createdTime": "2024-02-10T07:58:21.000Z",
    "fields": {
      "Name": "Applications of Differential Calculus",
      "Item ID": "65c7257ad92b5470dcc3c8c2",
      "Slug": "differential-calculus-applications",
      "Nodes": [
        "rec7T99TpcQy7UPcm",
        "rec5Iu355VQqvY04d",
        "rechNTAYHib2WjS0m",
        "recEFXbRrJv1l0pWy",
        "recdEKzOGKyvzMzKz"
      ],
      "Version": 1,
      "Description": "This track focuses on applications of Differential Calculus such as derivative tests, minima and maxima, and optimization problems.\n"
    }
  }
]

export default tracksDatabase