// Complete relatedlinks and summary

let sampleData = [
    {
        "id": "root",
        "name": "Root",
        "courseMapName": "Root",
        "parentId": "",
        "link": "https://wethestudy.webflow.io/learn/root",
        "order": "",
        "category": "",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "fluid-mechanics-fundamentals",
        "name": "Fluid Mechanics: Fundamentals",
        "courseMapName": "Fundamentals",
        "parentId": "fluid-mechanics",
        "link": "https://wethestudy.webflow.io/learn/fluid-mechanics-fundamentals",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "net-work",
        "name": "Net Work",
        "courseMapName": "Net Work",
        "parentId": "work-and-energy",
        "link": "https://wethestudy.webflow.io/learn/net-work",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "free-fall-with-resistance-model-derivation",
        "name": "Free Fall with Resistance: Model Derivation",
        "courseMapName": "Model Derivation",
        "parentId": "modeling-free-fall-motion-with-air-resistance",
        "link": "https://wethestudy.webflow.io/learn/free-fall-with-resistance-model-derivation",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": ["differential-equations"]
    },
    {
        "id": "free-falling-bodies",
        "name": "Free Falling Bodies",
        "courseMapName": "Free-Falling Bodies",
        "parentId": "motion",
        "link": "https://wethestudy.webflow.io/learn/free-falling-bodies",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "motion",
        "name": "Motion",
        "courseMapName": "Motion",
        "parentId": "kinematics",
        "link": "https://wethestudy.webflow.io/learn/motion",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "fluid-mechanics",
        "name": "Fluid Mechanics",
        "courseMapName": "Fluid Mechanics",
        "parentId": "mechanics",
        "link": "https://wethestudy.webflow.io/learn/fluid-mechanics",
        "order": "5",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "strength-of-materials",
        "name": "Strength of Materials",
        "courseMapName": "Strength of Materials",
        "parentId": "mechanics",
        "link": "https://wethestudy.webflow.io/learn/strength-of-materials",
        "order": "4",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "work-and-energy",
        "name": "Work and Energy",
        "courseMapName": "Work and Energy",
        "parentId": "mechanics",
        "link": "https://wethestudy.webflow.io/learn/work-and-energy",
        "order": "3",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "kinetics",
        "name": "Kinetics",
        "courseMapName": "Kinetics",
        "parentId": "mechanics",
        "link": "https://wethestudy.webflow.io/learn/kinetics",
        "order": "2",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "kinematics",
        "name": "Kinematics",
        "courseMapName": "Kinematics",
        "parentId": "mechanics",
        "link": "https://wethestudy.webflow.io/learn/kinematics",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "mechanics",
        "name": "Mechanics",
        "courseMapName": "Mechanics",
        "parentId": "physics",
        "link": "https://wethestudy.webflow.io/learn/mechanics",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "physics",
        "name": "Physics",
        "courseMapName": "Physics",
        "parentId": "root",
        "link": "https://wethestudy.webflow.io/learn/physics",
        "order": "2",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "frame-analysis-internal-force-and-stresses",
        "name": "Frame Analysis: Internal Force and Stresses",
        "courseMapName": "Internal Force and Stresses",
        "parentId": "rigid-portal-frame-analysis",
        "link": "https://wethestudy.webflow.io/learn/frame-analysis-internal-force-and-stresses",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "beam-analysis-deflection",
        "name": "Beam Analysis: Deflection",
        "courseMapName": "Deflection",
        "parentId": "simple-beam-analysis",
        "link": "https://wethestudy.webflow.io/learn/beam-analysis-deflection",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "beam-analysis-internal-force-and-stresses",
        "name": "Beam Analysis: Internal Force and Stresses",
        "courseMapName": "Internal Force and Stresses",
        "parentId": "simple-beam-analysis",
        "link": "https://wethestudy.webflow.io/learn/beam-analysis-internal-force-and-stresses",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "truss-analysis-internal-force-and-stresses",
        "name": "Truss Analysis: Internal Force and Stresses",
        "courseMapName": "Internal Force and Stresses",
        "parentId": "simple-truss-analysis",
        "link": "https://wethestudy.webflow.io/learn/truss-analysis-internal-force-and-stresses",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "frame-analysis-examples",
        "name": "Frame Analysis Examples",
        "courseMapName": "Frame Analysis Examples",
        "parentId": "structural-frame",
        "link": "https://wethestudy.webflow.io/learn/frame-analysis-examples",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "beam-analysis-examples",
        "name": "Beam Analysis Examples",
        "courseMapName": "Beam Analysis Examples",
        "parentId": "structural-beam",
        "link": "https://wethestudy.webflow.io/learn/beam-analysis-examples",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "truss-analysis-examples",
        "name": "Truss Analysis Examples",
        "courseMapName": "Truss Analysis Examples",
        "parentId": "structural-truss",
        "link": "https://wethestudy.webflow.io/learn/truss-analysis-examples",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-frame",
        "name": "Structural Frame",
        "courseMapName": "Structural Frame",
        "parentId": "structural-analysis-applications",
        "link": "https://wethestudy.webflow.io/learn/structural-frame",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-beam",
        "name": "Structural Beam",
        "courseMapName": "Structural Beam",
        "parentId": "structural-analysis-applications",
        "link": "https://wethestudy.webflow.io/learn/structural-beam",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-truss",
        "name": "Structural Truss",
        "courseMapName": "Structural Truss",
        "parentId": "structural-analysis-applications",
        "link": "https://wethestudy.webflow.io/learn/structural-truss",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "deflection-methods",
        "name": "Deflection: Methods",
        "courseMapName": "Methods",
        "parentId": "analysis-deflections",
        "link": "https://wethestudy.webflow.io/learn/deflection-methods",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "deflection-basics",
        "name": "Deflection: Basics",
        "courseMapName": "Basics",
        "parentId": "analysis-deflections",
        "link": "https://wethestudy.webflow.io/learn/deflection-basics",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "modeling-axial-forces",
        "name": "Modeling Axial Forces",
        "courseMapName": "Modeling Axial Forces",
        "parentId": "analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/modeling-axial-forces",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analysis-deflections",
        "name": "Analysis: Deflections",
        "courseMapName": "Deflections",
        "parentId": "classical-approach-analysis-methods",
        "link": "https://wethestudy.webflow.io/learn/analysis-deflections",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analysis-internal-force-and-stresses",
        "name": "Analysis: Internal Force and Stresses",
        "courseMapName": "Internal Force and Stresses",
        "parentId": "classical-approach-analysis-methods",
        "link": "https://wethestudy.webflow.io/learn/analysis-internal-force-and-stresses",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "classical-approach-analysis-methods",
        "name": "Classical Approach: Analysis Methods",
        "courseMapName": "Analysis Methods",
        "parentId": "classical-approach",
        "link": "https://wethestudy.webflow.io/learn/classical-approach-analysis-methods",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "classical-approach",
        "name": "Classical Approach",
        "courseMapName": "Classical Approach",
        "parentId": "structural-analysis-theory",
        "link": "https://wethestudy.webflow.io/learn/classical-approach",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-analysis-applications",
        "name": "Structural Analysis: Applications",
        "courseMapName": "Applications",
        "parentId": "structural-analysis",
        "link": "https://wethestudy.webflow.io/learn/structural-analysis-applications",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-analysis-theory",
        "name": "Structural Analysis: Theory",
        "courseMapName": "Theory",
        "parentId": "structural-analysis",
        "link": "https://wethestudy.webflow.io/learn/structural-analysis-theory",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-loads",
        "name": "Structural Loads",
        "courseMapName": "Structural Loads",
        "parentId": "structural-engineering",
        "link": "https://wethestudy.webflow.io/learn/structural-loads",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-modeling",
        "name": "Structural Modeling",
        "courseMapName": "Structural Modeling",
        "parentId": "structural-engineering",
        "link": "https://wethestudy.webflow.io/learn/structural-modeling",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structure-basics",
        "name": "Structure: Basics",
        "courseMapName": "Basics",
        "parentId": "structural-engineering",
        "link": "https://wethestudy.webflow.io/learn/structure-basics",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-engineering",
        "name": "Structural Engineering",
        "courseMapName": "Structural Engineering",
        "parentId": "engineering",
        "link": "https://wethestudy.webflow.io/learn/structural-engineering",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "engineering",
        "name": "Engineering",
        "courseMapName": "Engineering",
        "parentId": "root",
        "link": "https://wethestudy.webflow.io/learn/engineering",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structures",
        "name": "Structures",
        "courseMapName": "Structures",
        "parentId": "mathematics",
        "link": "https://wethestudy.webflow.io/learn/structures",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "geometry",
        "name": "Geometry",
        "courseMapName": "Geometry",
        "parentId": "mathematics",
        "link": "https://wethestudy.webflow.io/learn/geometry",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "mathematics",
        "name": "Mathematics",
        "courseMapName": "Mathematics",
        "parentId": "root",
        "link": "https://wethestudy.webflow.io/learn/mathematics",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "trigonometric-identities",
        "name": "Trigonometric Identities",
        "courseMapName": "Identities",
        "parentId": "trigonometry",
        "link": "https://wethestudy.webflow.io/learn/trigonometric-identities",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "trigonometry",
        "name": "Trigonometry",
        "courseMapName": "Trigonometry",
        "parentId": "geometry",
        "link": "https://wethestudy.webflow.io/learn/trigonometry",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integral-calculus",
        "name": "Integral Calculus",
        "courseMapName": "Integral Calculus",
        "parentId": "calculus",
        "link": "https://wethestudy.webflow.io/learn/integral-calculus",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "derivatives",
        "name": "Derivatives",
        "courseMapName": "Derivatives",
        "parentId": "differential-calculus",
        "link": "https://wethestudy.webflow.io/learn/derivatives",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "algebra",
        "name": "Algebra",
        "courseMapName": "Algebra",
        "parentId": "structures",
        "link": "https://wethestudy.webflow.io/learn/algebra",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "relations-and-functions",
        "name": "Relations and Functions",
        "courseMapName": "Relations and Functions",
        "parentId": "structures",
        "link": "https://wethestudy.webflow.io/learn/relations-and-functions",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "calculus",
        "name": "Calculus",
        "courseMapName": "Calculus",
        "parentId": "mathematics",
        "link": "https://wethestudy.webflow.io/learn/calculus",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "differential-calculus",
        "name": "Differential Calculus",
        "courseMapName": "Differential Calculus",
        "parentId": "calculus",
        "link": "https://wethestudy.webflow.io/learn/differential-calculus",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "differential-equations-solutions",
        "name": "Differential Equations: Solutions",
        "courseMapName": "Solutions",
        "parentId": "differential-equations",
        "link": "https://wethestudy.webflow.io/learn/differential-equations-solutions",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "differential-equations",
        "name": "Differential Equations",
        "courseMapName": "Differential Equations",
        "parentId": "calculus",
        "link": "https://wethestudy.webflow.io/learn/differential-equations",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "the-conics",
        "name": "The Conics",
        "courseMapName": "Conics",
        "parentId": "conic-sections",
        "link": "https://wethestudy.webflow.io/learn/the-conics",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analytic-geometry",
        "name": "Analytic Geometry",
        "courseMapName": "Analytic Geometry",
        "parentId": "geometry",
        "link": "https://wethestudy.webflow.io/learn/analytic-geometry",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-terminal-velocity",
        "name": "What is Terminal Velocity?",
        "courseMapName": "Terminal Velocity",
        "parentId": "modeling-free-fall-motion-with-air-resistance",
        "link": "https://wethestudy.webflow.io/learn/what-is-terminal-velocity",
        "order": "3",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "work-integration",
        "name": "Work: Integration",
        "courseMapName": "Integration",
        "parentId": "net-work",
        "link": "https://wethestudy.webflow.io/learn/work-integration",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": ['integration-area-between-curves']
    },
    {
        "id": "what-is-pascals-principle",
        "name": "What is Pascal's Principle",
        "courseMapName": "Pascal's Principle",
        "parentId": "fluid-pressure",
        "link": "https://wethestudy.webflow.io/learn/what-is-pascals-principle",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-gravitational-force",
        "name": "What is Gravitational Force?",
        "courseMapName": "Gravitational Force",
        "parentId": "kinetics",
        "link": "https://wethestudy.webflow.io/learn/what-is-gravitational-force",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-fluid-resistance",
        "name": "What is Fluid Resistance?",
        "courseMapName": "Fluid Resistance",
        "parentId": "fluid-mechanics-fundamentals",
        "link": "https://wethestudy.webflow.io/learn/what-is-fluid-resistance",
        "order": "3",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-fluid-force",
        "name": "What is Fluid Force?",
        "courseMapName": "Fluid Force",
        "parentId": "fluid-mechanics-fundamentals",
        "link": "https://wethestudy.webflow.io/learn/what-is-fluid-force",
        "order": "2",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-drag-equation",
        "name": "What is Drag Equation?",
        "courseMapName": "Drag Equation",
        "parentId": "what-is-fluid-resistance",
        "link": "https://wethestudy.webflow.io/learn/what-is-drag-equation",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "types-of-internal-forces",
        "name": "Types of Internal Forces",
        "courseMapName": "Types",
        "parentId": "investigating-internal-forces",
        "link": "https://wethestudy.webflow.io/learn/types-of-internal-forces",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "modeling-free-fall-motion-with-air-resistance",
        "name": "Modeling Free Fall Motion with Air Resistance",
        "courseMapName": "Free Fall with Air Resistance",
        "parentId": "free-falling-bodies",
        "link": "https://wethestudy.webflow.io/learn/modeling-free-fall-motion-with-air-resistance",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "free-fall-motion-with-drag-resistance-velocity-time",
        "name": "Free-Fall Motion with Drag Resistance: Velocity-Time",
        "courseMapName": "Velocity-Time",
        "parentId": "free-fall-with-resistance-model-derivation",
        "link": "https://wethestudy.webflow.io/learn/free-fall-motion-with-drag-resistance-velocity-time",
        "order": "2",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": ["differential-equations", "analytical-approach-first-order-linear-differential-equation"]
    },
    {
        "id": "investigating-internal-forces",
        "name": "Investigating Internal Forces",
        "courseMapName": "Internal Forces",
        "parentId": "strength-of-materials",
        "link": "https://wethestudy.webflow.io/learn/investigating-internal-forces",
        "order": "2",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "free-fall-motion-with-simple-resistance-velocity-time",
        "name": "Free Fall Motion with Simple Resistance: Velocity-Time",
        "courseMapName": "Velocity-Time: Simple",
        "parentId": "free-fall-with-resistance-model-derivation",
        "link": "https://wethestudy.webflow.io/learn/free-fall-motion-with-simple-resistance-velocity-time",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "external-and-internal-forces",
        "name": "External and Internal Forces",
        "courseMapName": "External and Internal Forces",
        "parentId": "strength-of-materials",
        "link": "https://wethestudy.webflow.io/learn/external-and-internal-forces",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "free-fall-motion-with-drag-resistance-acceleration-time",
        "name": "Free-Fall Motion with Drag Resistance: Acceleration-Time",
        "courseMapName": "Acceleration-Time",
        "parentId": "free-fall-with-resistance-model-derivation",
        "link": "https://wethestudy.webflow.io/learn/free-fall-motion-with-drag-resistance-acceleration-time",
        "order": "3",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "fluid-pressure",
        "name": "Fluid Pressure",
        "courseMapName": "Fluid Pressure",
        "parentId": "fluid-mechanics-fundamentals",
        "link": "https://wethestudy.webflow.io/learn/fluid-pressure",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "fluid-force-integration",
        "name": "Fluid Force: Integration",
        "courseMapName": "Integration",
        "parentId": "what-is-fluid-force",
        "link": "https://wethestudy.webflow.io/learn/fluid-force-integration",
        "order": "1",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "free-fall-motion-with-drag-resistance-position-time",
        "name": "Free-Fall Motion with Drag Resistance: Position-Time",
        "courseMapName": "Position-Time",
        "parentId": "free-fall-with-resistance-model-derivation",
        "link": "https://wethestudy.webflow.io/learn/free-fall-motion-with-drag-resistance-position-time",
        "order": "4",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "application-free-fall-motion-with-drag-air-resistance",
        "name": "Application: Free Fall Motion with Drag Air Resistance",
        "courseMapName": "Free Fall Motion with Drag",
        "parentId": "modeling-free-fall-motion-with-air-resistance",
        "link": "https://wethestudy.webflow.io/learn/application-free-fall-motion-with-drag-air-resistance",
        "order": "2",
        "category": "Physics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "work-methods-beam-analysis",
        "name": "Work Methods: Beam Analysis",
        "courseMapName": "Beam Analysis",
        "parentId": "beam-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/work-methods-beam-analysis",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analysis-work-and-energy",
        "name": "Analysis: Work and Energy",
        "courseMapName": "Work and Energy",
        "parentId": "structural-concepts",
        "link": "https://wethestudy.webflow.io/learn/analysis-work-and-energy",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "where-do-loads-come-from",
        "name": "Where Do Loads Come From?",
        "courseMapName": "Load Origin",
        "parentId": "structural-loads",
        "link": "https://wethestudy.webflow.io/learn/where-do-loads-come-from",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "virual-work-axial-strains-simple-truss",
        "name": "Virtual Work: Axial Strains - Simple Truss",
        "courseMapName": "Axial Strains - Simple Truss",
        "parentId": "truss-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/virual-work-axial-strains-simple-truss",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-a-truss",
        "name": "What is a Truss?",
        "courseMapName": "Truss",
        "parentId": "basic-structural-units",
        "link": "https://wethestudy.webflow.io/learn/what-is-a-truss",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-a-structure",
        "name": "What is a Structure?",
        "courseMapName": "Structure",
        "parentId": "structure-basics",
        "link": "https://wethestudy.webflow.io/learn/what-is-a-structure",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "virtual-work-notation",
        "name": "Virtual Work: Notation",
        "courseMapName": "Notation",
        "parentId": "virtual-work-deflection",
        "link": "https://wethestudy.webflow.io/learn/virtual-work-notation",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-are-structural-loads",
        "name": "What Are Structural Loads?",
        "courseMapName": "Structural Loads",
        "parentId": "structural-loads",
        "link": "https://wethestudy.webflow.io/learn/what-are-structural-loads",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "virtual-work-flexural-strains-simple-beam",
        "name": "Virtual Work: Flexural Strains - Simple Beam",
        "courseMapName": "Flexural Strains - Simple Beam",
        "parentId": "beam-analysis-deflection",
        "link": "https://wethestudy.webflow.io/learn/virtual-work-flexural-strains-simple-beam",
        "order": "8",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "virtual-work-flexural-strains",
        "name": "Virtual Work: Flexural Strains",
        "courseMapName": "Flexural Strains",
        "parentId": "virtual-work-deflection",
        "link": "https://wethestudy.webflow.io/learn/virtual-work-flexural-strains",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "virtual-work-deflection",
        "name": "Virtual Work: Deflections",
        "courseMapName": "Deflections",
        "parentId": "introduction-to-work-methods",
        "link": "https://wethestudy.webflow.io/learn/virtual-work-deflection",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "virtual-work-beam-analysis",
        "name": "Virtual Work: Beam Analysis",
        "courseMapName": "Beam Analysis",
        "parentId": "beam-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/virtual-work-beam-analysis",
        "order": "5",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "virtual-work-axial-strains",
        "name": "Virtual Work: Axial Strains",
        "courseMapName": "Axial Strains",
        "parentId": "virtual-work-deflection",
        "link": "https://wethestudy.webflow.io/learn/virtual-work-axial-strains",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "truss-types-by-configuration",
        "name": "Truss Types By Configuration",
        "courseMapName": "Configuration",
        "parentId": "what-is-a-truss",
        "link": "https://wethestudy.webflow.io/learn/truss-types-by-configuration",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "truss-stability",
        "name": "Truss Stability",
        "courseMapName": "Truss Stability",
        "parentId": "simple-truss-analysis",
        "link": "https://wethestudy.webflow.io/learn/truss-stability",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-rigidity",
        "name": "Structural Rigidity",
        "courseMapName": "Structural Rigidity",
        "parentId": "structural-material",
        "link": "https://wethestudy.webflow.io/learn/structural-rigidity",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "superposition",
        "name": "Superposition",
        "courseMapName": "Superposition",
        "parentId": "structural-concepts",
        "link": "https://wethestudy.webflow.io/learn/superposition",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-supports",
        "name": "Structural Supports",
        "courseMapName": "Structural Supports",
        "parentId": "structural-model",
        "link": "https://wethestudy.webflow.io/learn/structural-supports",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-references",
        "name": "Structural References",
        "courseMapName": "Structural References",
        "parentId": "structural-model",
        "link": "https://wethestudy.webflow.io/learn/structural-references",
        "order": "5",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-model",
        "name": "Structural Model",
        "courseMapName": "Structural Model",
        "parentId": "structural-modeling",
        "link": "https://wethestudy.webflow.io/learn/structural-model",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-member",
        "name": "Structural Member",
        "courseMapName": "Structural Member",
        "parentId": "structural-model",
        "link": "https://wethestudy.webflow.io/learn/structural-member",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-material",
        "name": "Structural Material",
        "courseMapName": "Material",
        "parentId": "structural-model",
        "link": "https://wethestudy.webflow.io/learn/structural-material",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-analysis",
        "name": "Structural Analysis",
        "courseMapName": "Structural Analysis",
        "parentId": "structural-engineering",
        "link": "https://wethestudy.webflow.io/learn/structural-analysis",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-joints-and-connections",
        "name": "Structural Joints and Connections",
        "courseMapName": "Joints and Connections",
        "parentId": "structural-model",
        "link": "https://wethestudy.webflow.io/learn/structural-joints-and-connections",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "structural-concepts",
        "name": "Structural Concepts",
        "courseMapName": "Structural Concepts",
        "parentId": "classical-approach",
        "link": "https://wethestudy.webflow.io/learn/structural-concepts",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "statically-determinate-and-indeterminate-structures",
        "name": "Statically Determinate and Indeterminate Structures",
        "courseMapName": "Statically Determinate and Indeterminate",
        "parentId": "analysis-types",
        "link": "https://wethestudy.webflow.io/learn/statically-determinate-and-indeterminate-structures",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "static-and-dynamic-analysis",
        "name": "Static and Dynamic Analysis",
        "courseMapName": "Static and Dynamic Analysis",
        "parentId": "analysis-types",
        "link": "https://wethestudy.webflow.io/learn/static-and-dynamic-analysis",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "special-compound-truss-analysis",
        "name": "Special Compound Truss Analysis",
        "courseMapName": "Special Compound Truss",
        "parentId": "truss-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/special-compound-truss-analysis",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "simple-truss-analysis",
        "name": "Simple Truss Analysis",
        "courseMapName": "Truss Analysis",
        "parentId": "structural-truss",
        "link": "https://wethestudy.webflow.io/learn/simple-truss-analysis",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "simple-beam-analysis",
        "name": "Simple Beam Analysis",
        "courseMapName": "Beam Analysis",
        "parentId": "structural-beam",
        "link": "https://wethestudy.webflow.io/learn/simple-beam-analysis",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "shear-and-moment-relationships-simple-beam",
        "name": "Shear and Moment Relationships: Simple Beam",
        "courseMapName": "Shear and Moment",
        "parentId": "beam-analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/shear-and-moment-relationships-simple-beam",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "rigid-portal-frame-analysis",
        "name": "Rigid Portal Frame Analysis",
        "courseMapName": "Rigid Portal Frame",
        "parentId": "structural-frame",
        "link": "https://wethestudy.webflow.io/learn/rigid-portal-frame-analysis",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "shear-and-moment-equations-simple-beam",
        "name": "Shear and Moment Equations: Simple Beam",
        "courseMapName": "Shear and Moment Equations",
        "parentId": "beam-analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/shear-and-moment-equations-simple-beam",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "rigid-gable-frame-analysis",
        "name": "Rigid Gable Frame Analysis",
        "courseMapName": "Rigid Gable Frame",
        "parentId": "frame-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/rigid-gable-frame-analysis",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "real-work-flexural-strains",
        "name": "Real Work: Flexural Strains",
        "courseMapName": "Flexural Strains",
        "parentId": "real-work",
        "link": "https://wethestudy.webflow.io/learn/real-work-flexural-strains",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "real-work-flexural-strains-simple-beam",
        "name": "Real Work: Flexural Strains - Simple Beam",
        "courseMapName": "Flexural Strains - Simple Beam",
        "parentId": "beam-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/real-work-flexural-strains-simple-beam",
        "order": "6",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "point-of-zero-moment-simple-beam",
        "name": "Point of Zero Moment: Simple Beam",
        "courseMapName": "Point of Zero Moment",
        "parentId": "beam-analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/point-of-zero-moment-simple-beam",
        "order": "5",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "real-work-axial-strains-simple-truss",
        "name": "Real Work: Axial Strains - Simple Truss",
        "courseMapName": "Axial Strains - Simple Truss",
        "parentId": "truss-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/real-work-axial-strains-simple-truss",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "real-work-axial-strains",
        "name": "Real Work: Axial Strains",
        "courseMapName": "Axial Strains",
        "parentId": "real-work",
        "link": "https://wethestudy.webflow.io/learn/real-work-axial-strains",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "real-work",
        "name": "Real Work",
        "courseMapName": "Real Work",
        "parentId": "introduction-to-work-methods",
        "link": "https://wethestudy.webflow.io/learn/real-work",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "point-of-zero-shear-simple-beam",
        "name": "Point of Zero Shear: Simple Beam",
        "courseMapName": "Point of Zero Shear",
        "parentId": "beam-analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/point-of-zero-shear-simple-beam",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "pin-connected-frame-analysis",
        "name": "Pin-Connected Frame Analysis",
        "courseMapName": "Pin-Connected Frame",
        "parentId": "frame-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/pin-connected-frame-analysis",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "plane-and-spatial-structures",
        "name": "Plane and Spatial Structures",
        "courseMapName": "Plane and Spatial Structures",
        "parentId": "analysis-types",
        "link": "https://wethestudy.webflow.io/learn/plane-and-spatial-structures",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "parts-of-a-truss",
        "name": "Parts of A Truss",
        "courseMapName": "Parts",
        "parentId": "what-is-a-truss",
        "link": "https://wethestudy.webflow.io/learn/parts-of-a-truss",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "partial-derivative-method-flexural-strains-simple-beam",
        "name": "Partial Derivative Method: Flexural Strains - Simple Beam",
        "courseMapName": "Flexural Strains - Simple Beam",
        "parentId": "beam-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/partial-derivative-method-flexural-strains-simple-beam",
        "order": "7",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "partial-derivative-method-flexural-strains",
        "name": "Partial Derivative Method: Flexural Strains",
        "courseMapName": "Flexural Strains",
        "parentId": "partial-derivative-method",
        "link": "https://wethestudy.webflow.io/learn/partial-derivative-method-flexural-strains",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "partial-derivative-method-axial-strains-determinate-truss",
        "name": "Partial Derivative Method: Axial Strains - Determinate Truss",
        "courseMapName": "Determinate Truss",
        "parentId": "truss-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/partial-derivative-method-axial-strains-determinate-truss",
        "order": "5",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "partial-derivative-method-axial-strains",
        "name": "Partial Derivative Method: Axial Strains",
        "courseMapName": "Axial Strains",
        "parentId": "partial-derivative-method",
        "link": "https://wethestudy.webflow.io/learn/partial-derivative-method-axial-strains",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "partial-derivative-method",
        "name": "Partial Derivative Method",
        "courseMapName": "Partial Derivative Method",
        "parentId": "introduction-to-work-methods",
        "link": "https://wethestudy.webflow.io/learn/partial-derivative-method",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "moment-by-parts-simple-beam",
        "name": "Moment By Parts: Simple Beam",
        "courseMapName": "Example",
        "parentId": "moment-by-parts",
        "link": "https://wethestudy.webflow.io/learn/moment-by-parts-simple-beam",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "moment-by-parts",
        "name": "Moment By Parts",
        "courseMapName": "Moment By Parts",
        "parentId": "beam-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/moment-by-parts",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "modeling-shear-and-moment",
        "name": "Modeling Shear and Moment",
        "courseMapName": "Modeling Shear and Moment",
        "parentId": "analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/modeling-shear-and-moment",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "method-of-sections-simple-truss",
        "name": "Method of Sections: Simple Truss",
        "courseMapName": "Method of Sections",
        "parentId": "truss-analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/method-of-sections-simple-truss",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "method-of-joints-simple-truss",
        "name": "Method of Joints: Simple Truss",
        "courseMapName": "Method of Joints",
        "parentId": "truss-analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/method-of-joints-simple-truss",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "method-of-sections",
        "name": "Method of Sections",
        "courseMapName": "Method of Sections",
        "parentId": "modeling-axial-forces",
        "link": "https://wethestudy.webflow.io/learn/method-of-sections",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "method-of-joints",
        "name": "Method of Joints",
        "courseMapName": "Method of Joints",
        "parentId": "modeling-axial-forces",
        "link": "https://wethestudy.webflow.io/learn/method-of-joints",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "method-of-bar-conversions",
        "name": "Method of Bar Conversions",
        "courseMapName": "Bar Conversions",
        "parentId": "modeling-axial-forces",
        "link": "https://wethestudy.webflow.io/learn/method-of-bar-conversions",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "method-of-bar-conversions-complex-truss",
        "name": "Method of Bar Conversions: Complex Truss",
        "courseMapName": "Complex Truss Analysis",
        "parentId": "complex-truss-analysis",
        "link": "https://wethestudy.webflow.io/learn/method-of-bar-conversions-complex-truss",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "member-longitudinal-properties",
        "name": "Member: Longitudinal Properties",
        "courseMapName": "Longitudinal Properties",
        "parentId": "structural-member",
        "link": "https://wethestudy.webflow.io/learn/member-longitudinal-properties",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "member-cross-section-properties",
        "name": "Member: Cross-Section Properties",
        "courseMapName": "Cross-Section Properties",
        "parentId": "structural-member",
        "link": "https://wethestudy.webflow.io/learn/member-cross-section-properties",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "load-types",
        "name": "Load Types",
        "courseMapName": "Load Types",
        "parentId": "structural-loads",
        "link": "https://wethestudy.webflow.io/learn/load-types",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "load-spatial-application",
        "name": "Load Spatial Application",
        "courseMapName": "Spatial Application",
        "parentId": "structural-loads",
        "link": "https://wethestudy.webflow.io/learn/load-spatial-application",
        "order": "5",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "load-and-shear-relationships-simple-beam",
        "name": "Load and Shear Relationships: Simple Beam",
        "courseMapName": "Load and Shear",
        "parentId": "beam-analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/load-and-shear-relationships-simple-beam",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "load-properties",
        "name": "Load Properties",
        "courseMapName": "Load Properties",
        "parentId": "structural-loads",
        "link": "https://wethestudy.webflow.io/learn/load-properties",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "load-shear-and-moment-relationships",
        "name": "Load, Shear, and Moment Relationships",
        "courseMapName": "Load, Shear, and Moment Relationships",
        "parentId": "modeling-shear-and-moment",
        "link": "https://wethestudy.webflow.io/learn/load-shear-and-moment-relationships",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "key-analysis-concepts",
        "name": "Key Analysis Concepts",
        "courseMapName": "Key Analysis Concepts",
        "parentId": "structural-analysis-theory",
        "link": "https://wethestudy.webflow.io/learn/key-analysis-concepts",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "linear-and-nonlinear-analysis",
        "name": "Linear and Nonlinear Analysis",
        "courseMapName": "Linear and Nonlinear Analysis",
        "parentId": "analysis-types",
        "link": "https://wethestudy.webflow.io/learn/linear-and-nonlinear-analysis",
        "order": "5",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "how-to-design-structures",
        "name": "How to Design Structures?",
        "courseMapName": "Design Basics",
        "parentId": "structure-basics",
        "link": "https://wethestudy.webflow.io/learn/how-to-design-structures",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "introduction-to-work-methods",
        "name": "Introduction to Work Methods",
        "courseMapName": "Work Methods",
        "parentId": "deflection-methods",
        "link": "https://wethestudy.webflow.io/learn/introduction-to-work-methods",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "how-do-we-categorize-structures",
        "name": "How Do We Categorize Structures?",
        "courseMapName": "Categorization",
        "parentId": "structure-basics",
        "link": "https://wethestudy.webflow.io/learn/how-do-we-categorize-structures",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "geometric-stability",
        "name": "Geometric Stability",
        "courseMapName": "Stability",
        "parentId": "classical-approach-analysis-methods",
        "link": "https://wethestudy.webflow.io/learn/geometric-stability",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "frame-types-by-configuration",
        "name": "Frame Types By Configuration",
        "courseMapName": "Configuration",
        "parentId": "what-is-a-frame",
        "link": "https://wethestudy.webflow.io/learn/frame-types-by-configuration",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "frame-stability",
        "name": "Frame Stability",
        "courseMapName": "Stability",
        "parentId": "rigid-portal-frame-analysis",
        "link": "https://wethestudy.webflow.io/learn/frame-stability",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "frame-arrangement",
        "name": "Frame Arrangement",
        "courseMapName": "Arrangement",
        "parentId": "what-is-a-frame",
        "link": "https://wethestudy.webflow.io/learn/frame-arrangement",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-a-frame",
        "name": "What is a Frame?",
        "courseMapName": "Frame",
        "parentId": "basic-structural-units",
        "link": "https://wethestudy.webflow.io/learn/what-is-a-frame",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "force-analysis-rigid-portal-frame",
        "name": "Force Analysis: Rigid Portal Frame",
        "courseMapName": "Force Analysis",
        "parentId": "frame-analysis-internal-force-and-stresses",
        "link": "https://wethestudy.webflow.io/learn/force-analysis-rigid-portal-frame",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "force-analysis-pin-connected-frame",
        "name": "Force Analysis: Pin-Connected Frame",
        "courseMapName": "Force Analysis",
        "parentId": "pin-connected-frame-analysis",
        "link": "https://wethestudy.webflow.io/learn/force-analysis-pin-connected-frame",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "force-analysis-rigid-gable-frame",
        "name": "Force Analysis: Rigid Gable Frame",
        "courseMapName": "Force Analysis",
        "parentId": "rigid-gable-frame-analysis",
        "link": "https://wethestudy.webflow.io/learn/force-analysis-rigid-gable-frame",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "double-integration-method-segment-analysis",
        "name": "Double Integration Method: Segment Analysis",
        "courseMapName": "Segment Analysis",
        "parentId": "beam-analysis-deflection",
        "link": "https://wethestudy.webflow.io/learn/double-integration-method-segment-analysis",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "evaluating-shear-and-moment",
        "name": "Evaluating Shear and Moment",
        "courseMapName": "Evaluation",
        "parentId": "modeling-shear-and-moment",
        "link": "https://wethestudy.webflow.io/learn/evaluating-shear-and-moment",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "equilibrium-principle",
        "name": "Equilibrium Principle",
        "courseMapName": "Equilibrium",
        "parentId": "key-analysis-concepts",
        "link": "https://wethestudy.webflow.io/learn/equilibrium-principle",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "double-integration-method-general-equation-analysis",
        "name": "Double Integration Method: General Equation Analysis",
        "courseMapName": "General Equation",
        "parentId": "beam-analysis-deflection",
        "link": "https://wethestudy.webflow.io/learn/double-integration-method-general-equation-analysis",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "double-integration-method-evaluating-deflections",
        "name": "Double Integration Method: Evaluating Deflections",
        "courseMapName": "Evaluating Deflections",
        "parentId": "beam-analysis-deflection",
        "link": "https://wethestudy.webflow.io/learn/double-integration-method-evaluating-deflections",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "double-integration-method",
        "name": "Double Integration Method",
        "courseMapName": "Double Integration Method",
        "parentId": "deflection-methods",
        "link": "https://wethestudy.webflow.io/learn/double-integration-method",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "deflection-qualitative-analysis-of-flexural-members",
        "name": "Deflection: Qualitative Analysis of Flexural Members",
        "courseMapName": "Qualitative Analysis",
        "parentId": "deflection-basics",
        "link": "https://wethestudy.webflow.io/learn/deflection-qualitative-analysis-of-flexural-members",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "constitutive-equations",
        "name": "Constitutive Equations",
        "courseMapName": "Constitutive Equations",
        "parentId": "key-analysis-concepts",
        "link": "https://wethestudy.webflow.io/learn/constitutive-equations",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "conjugate-beam-method-simple-beam",
        "name": "Conjugate Beam Method: Simple Beam",
        "courseMapName": "Simple Beam",
        "parentId": "beam-analysis-deflection",
        "link": "https://wethestudy.webflow.io/learn/conjugate-beam-method-simple-beam",
        "order": "7",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "conjugate-beam-method-interpreting-directions",
        "name": "Conjugate Beam Method: Interpreting Directions",
        "courseMapName": "Directions",
        "parentId": "conjugate-beam-method",
        "link": "https://wethestudy.webflow.io/learn/conjugate-beam-method-interpreting-directions",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "conjugate-beam-method-conjugate-shear",
        "name": "Conjugate Beam Method: Conjugate Shear",
        "courseMapName": "Conjugate Shear",
        "parentId": "conjugate-beam-method",
        "link": "https://wethestudy.webflow.io/learn/conjugate-beam-method-conjugate-shear",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "conjugate-beam-method-conjugate-moment",
        "name": "Conjugate Beam Method: Conjugate Moment",
        "courseMapName": "Conjugate Moment",
        "parentId": "conjugate-beam-method",
        "link": "https://wethestudy.webflow.io/learn/conjugate-beam-method-conjugate-moment",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "conjugate-beam-method",
        "name": "Conjugate Beam Method",
        "courseMapName": "Conjugate Beam Method",
        "parentId": "deflection-methods",
        "link": "https://wethestudy.webflow.io/learn/conjugate-beam-method",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "conjugate-beam-method-artificial-constraints",
        "name": "Conjugate Beam Method: Artificial Constraints",
        "courseMapName": "Artificial Constraints",
        "parentId": "conjugate-beam-method",
        "link": "https://wethestudy.webflow.io/learn/conjugate-beam-method-artificial-constraints",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "compound-beam-analysis",
        "name": "Compound Beam Analysis",
        "courseMapName": "Compound Beam",
        "parentId": "beam-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/compound-beam-analysis",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "complex-truss-analysis",
        "name": "Complex Truss Analysis",
        "courseMapName": "Complex Truss",
        "parentId": "truss-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/complex-truss-analysis",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "compatibility-conditions",
        "name": "Compatibility Conditions",
        "courseMapName": "Compatibility",
        "parentId": "key-analysis-concepts",
        "link": "https://wethestudy.webflow.io/learn/compatibility-conditions",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "common-beam-types",
        "name": "Common Beam Types",
        "courseMapName": "Types",
        "parentId": "what-is-a-beam",
        "link": "https://wethestudy.webflow.io/learn/common-beam-types",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "common-truss-patterns",
        "name": "Common Truss Patterns",
        "courseMapName": "Truss Patterns",
        "parentId": "what-is-a-truss",
        "link": "https://wethestudy.webflow.io/learn/common-truss-patterns",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "cantilever-beam-deflection-patterns",
        "name": "Cantilever Beam Deflection Patterns",
        "courseMapName": "Deflection Patterns",
        "parentId": "deflection-methods",
        "link": "https://wethestudy.webflow.io/learn/cantilever-beam-deflection-patterns",
        "order": "5",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "cantilever-beam-patterns",
        "name": "Cantilever Beam Patterns",
        "courseMapName": "Cantilever Beam Patterns",
        "parentId": "cantilever-beam",
        "link": "https://wethestudy.webflow.io/learn/cantilever-beam-patterns",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "boundary-conditions",
        "name": "Boundary Conditions",
        "courseMapName": "Boundary Conditions",
        "parentId": "structural-concepts",
        "link": "https://wethestudy.webflow.io/learn/boundary-conditions",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "cantilever-beam",
        "name": "Cantilever Beam",
        "courseMapName": "Cantilever Beam",
        "parentId": "beam-analysis-examples",
        "link": "https://wethestudy.webflow.io/learn/cantilever-beam",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "bernoulli-euler-beam-theory",
        "name": "Bernoulli-Euler Beam Theory",
        "courseMapName": "Bernoulli-Euler Beam Theory",
        "parentId": "deflection-basics",
        "link": "https://wethestudy.webflow.io/learn/bernoulli-euler-beam-theory",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "beam-types-by-configuration",
        "name": "Beam Types By Configuration",
        "courseMapName": "Types",
        "parentId": "what-is-a-beam",
        "link": "https://wethestudy.webflow.io/learn/beam-types-by-configuration",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "beam-stability",
        "name": "Beam Stability",
        "courseMapName": "Stability",
        "parentId": "simple-beam-analysis",
        "link": "https://wethestudy.webflow.io/learn/beam-stability",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-a-beam",
        "name": "What is a Beam?",
        "courseMapName": "Beam",
        "parentId": "basic-structural-units",
        "link": "https://wethestudy.webflow.io/learn/what-is-a-beam",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "area-moment-method-tangential-deviation",
        "name": "Area Moment Method: Tangential Deviation",
        "courseMapName": "Tangential Deviation",
        "parentId": "area-moment-method",
        "link": "https://wethestudy.webflow.io/learn/area-moment-method-tangential-deviation",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "basic-structural-units",
        "name": "Basic Structural Units",
        "courseMapName": "Basic Structural Units",
        "parentId": "structural-modeling",
        "link": "https://wethestudy.webflow.io/learn/basic-structural-units",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "area-moment-method-moment-by-parts",
        "name": "Area Moment Method: Moment By Parts",
        "courseMapName": "Moment By Parts",
        "parentId": "beam-analysis-deflection",
        "link": "https://wethestudy.webflow.io/learn/area-moment-method-moment-by-parts",
        "order": "5",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "area-moment-method-maximum-deflection",
        "name": "Area Moment Method: Maximum Deflection",
        "courseMapName": "Maximum Deflection",
        "parentId": "beam-analysis-deflection",
        "link": "https://wethestudy.webflow.io/learn/area-moment-method-maximum-deflection",
        "order": "6",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "area-moment-method-integration",
        "name": "Area Moment Method: Integration",
        "courseMapName": "Integration",
        "parentId": "beam-analysis-deflection",
        "link": "https://wethestudy.webflow.io/learn/area-moment-method-integration",
        "order": "4",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "area-moment-method",
        "name": "Area Moment Method",
        "courseMapName": "Area Moment Method",
        "parentId": "deflection-methods",
        "link": "https://wethestudy.webflow.io/learn/area-moment-method",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "area-moment-method-change-in-slope",
        "name": "Area Moment Method: Change in Slope",
        "courseMapName": "Change in Slope",
        "parentId": "area-moment-method",
        "link": "https://wethestudy.webflow.io/learn/area-moment-method-change-in-slope",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analytical-model",
        "name": "Analytical Model",
        "courseMapName": "Analytical Model",
        "parentId": "structural-modeling",
        "link": "https://wethestudy.webflow.io/learn/analytical-model",
        "order": "3",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analysis-types",
        "name": "Analysis Types",
        "courseMapName": "Analysis Types",
        "parentId": "structural-analysis-theory",
        "link": "https://wethestudy.webflow.io/learn/analysis-types",
        "order": "2",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analysis-approaches",
        "name": "Classical and Matrix Approach",
        "courseMapName": "Classical and Matrix",
        "parentId": "analysis-types",
        "link": "https://wethestudy.webflow.io/learn/analysis-approaches",
        "order": "1",
        "category": "Engineering",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "why-learn-functions",
        "name": "Why Learn Functions?",
        "courseMapName": "Importance",
        "parentId": "mathematical-functions-basics",
        "link": "https://wethestudy.webflow.io/learn/why-learn-functions",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-the-newton-raphson-method",
        "name": "What is the Newton-Raphson Method?",
        "courseMapName": "Newton-Raphson Method",
        "parentId": "differential-calculus-applications",
        "link": "https://wethestudy.webflow.io/learn/what-is-the-newton-raphson-method",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-is-a-differential-equation",
        "name": "What is A Differential Equation?",
        "courseMapName": "Differential Equation",
        "parentId": "differential-equations",
        "link": "https://wethestudy.webflow.io/learn/what-is-a-differential-equation",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "what-are-mathematical-functions",
        "name": "What Are Mathematical Functions?",
        "courseMapName": "Functions",
        "parentId": "mathematical-functions-basics",
        "link": "https://wethestudy.webflow.io/learn/what-are-mathematical-functions",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "trigonometric-identity-hexagon-mnemonic",
        "name": "Trigonometric Identity: Hexagon Mnemonic",
        "courseMapName": "Hexagon Mnemonic",
        "parentId": "trigonometric-identities",
        "link": "https://wethestudy.webflow.io/learn/trigonometric-identity-hexagon-mnemonic",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "the-second-derivative",
        "name": "The Second Derivative",
        "courseMapName": "The Second Derivative",
        "parentId": "derivatives",
        "link": "https://wethestudy.webflow.io/learn/the-second-derivative",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "trigonometric-functions",
        "name": "Trigonometric Functions",
        "courseMapName": "Trigonometric Functions",
        "parentId": "function-types",
        "link": "https://wethestudy.webflow.io/learn/trigonometric-functions",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "the-right-triangle",
        "name": "The Right Triangle",
        "courseMapName": "Right Triangle",
        "parentId": "trigonometry",
        "link": "https://wethestudy.webflow.io/learn/the-right-triangle",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "the-meaning-behind-integration",
        "name": "The Meaning Behind Integration",
        "courseMapName": "Meaning Behind Integration",
        "parentId": "integral-calculus",
        "link": "https://wethestudy.webflow.io/learn/the-meaning-behind-integration",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "the-first-derivative",
        "name": "The First Derivative",
        "courseMapName": "First Derivative",
        "parentId": "derivatives",
        "link": "https://wethestudy.webflow.io/learn/the-first-derivative",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "parabola-orientations",
        "name": "Parabola: Orientations",
        "courseMapName": "Orientations",
        "parentId": "parabola",
        "link": "https://wethestudy.webflow.io/learn/parabola-orientations",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "polynomial-functions",
        "name": "Polynomial Functions",
        "courseMapName": "Polynomial Functions",
        "parentId": "function-types",
        "link": "https://wethestudy.webflow.io/learn/polynomial-functions",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "parabola-basic-geometry",
        "name": "Parabola: Basic Geometry",
        "courseMapName": "Basic Geometry",
        "parentId": "parabola",
        "link": "https://wethestudy.webflow.io/learn/parabola-basic-geometry",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "orthogonal-trajectories",
        "name": "Orthogonal Trajectories",
        "courseMapName": "Orthogonal Trajectories",
        "parentId": "differential-equations-applications",
        "link": "https://wethestudy.webflow.io/learn/orthogonal-trajectories",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "newtons-law-of-cooling",
        "name": "Newton's Law of Cooling",
        "courseMapName": "Newton's Law of Cooling",
        "parentId": "differential-equations-applications",
        "link": "https://wethestudy.webflow.io/learn/newtons-law-of-cooling",
        "order": "4",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "parabola",
        "name": "Parabola",
        "courseMapName": "Parabola",
        "parentId": "the-conics",
        "link": "https://wethestudy.webflow.io/learn/parabola",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "naming-mathematical-functions",
        "name": "Naming Mathematical Functions",
        "courseMapName": "Notation",
        "parentId": "constructing-mathematical-functions",
        "link": "https://wethestudy.webflow.io/learn/naming-mathematical-functions",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "monomials-and-polynomials",
        "name": "Monomials and Polynomials",
        "courseMapName": "Monomials and Polynomials",
        "parentId": "algebra",
        "link": "https://wethestudy.webflow.io/learn/monomials-and-polynomials",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "mathematical-functions-basics",
        "name": "Mathematical Functions: Basics",
        "courseMapName": "Basics",
        "parentId": "relations-and-functions",
        "link": "https://wethestudy.webflow.io/learn/mathematical-functions-basics",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "introduction-to-relations",
        "name": "Introduction to Relations",
        "courseMapName": "Relations",
        "parentId": "mathematical-functions-basics",
        "link": "https://wethestudy.webflow.io/learn/introduction-to-relations",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-volume-using-washers",
        "name": "Integration: Volume Using Washers",
        "courseMapName": "Washers",
        "parentId": "integration-volume",
        "link": "https://wethestudy.webflow.io/learn/integration-volume-using-washers",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "logistic-differential-equation",
        "name": "Logistic Differential Equation",
        "courseMapName": "Logistic",
        "parentId": "differential-equations-applications",
        "link": "https://wethestudy.webflow.io/learn/logistic-differential-equation",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-volume-using-shells",
        "name": "Integration: Volume Using Shells",
        "courseMapName": "Shells",
        "parentId": "integration-volume",
        "link": "https://wethestudy.webflow.io/learn/integration-volume-using-shells",
        "order": "4",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-volume-using-discs",
        "name": "Integration: Volume Using Discs",
        "courseMapName": "Discs",
        "parentId": "integration-volume",
        "link": "https://wethestudy.webflow.io/learn/integration-volume-using-discs",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-volume-by-cross-section",
        "name": "Integration: Volume By Cross-Section",
        "courseMapName": "Cross-Section",
        "parentId": "integration-volume",
        "link": "https://wethestudy.webflow.io/learn/integration-volume-by-cross-section",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-volume",
        "name": "Integration: Volume",
        "courseMapName": "Volume",
        "parentId": "the-meaning-behind-integration",
        "link": "https://wethestudy.webflow.io/learn/integration-volume",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-area-between-curves",
        "name": "Integration: Area Between Curves",
        "courseMapName": "Area Between Curves",
        "parentId": "integration-area",
        "link": "https://wethestudy.webflow.io/learn/integration-area-between-curves",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-surface-area",
        "name": "Integration: Surface Area",
        "courseMapName": "Surface Area",
        "parentId": "integration-area",
        "link": "https://wethestudy.webflow.io/learn/integration-surface-area",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-arc-of-a-curve",
        "name": "Integration: Arc of a Curve",
        "courseMapName": "Arc of a Curve",
        "parentId": "the-meaning-behind-integration",
        "link": "https://wethestudy.webflow.io/learn/integration-arc-of-a-curve",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "integration-area",
        "name": "Integration: Area",
        "courseMapName": "Area",
        "parentId": "the-meaning-behind-integration",
        "link": "https://wethestudy.webflow.io/learn/integration-area",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "growth-and-decay",
        "name": "Growth and Decay",
        "courseMapName": "Growth and Decay",
        "parentId": "differential-equations-applications",
        "link": "https://wethestudy.webflow.io/learn/growth-and-decay",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "general-versus-particular-solutions",
        "name": "General Versus Particular Solutions",
        "courseMapName": "General and Particular Solutions",
        "parentId": "differential-equations-solutions",
        "link": "https://wethestudy.webflow.io/learn/general-versus-particular-solutions",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "hyperbola-orientations",
        "name": "Hyperbola: Orientations",
        "courseMapName": "Orientation",
        "parentId": "hyperbola",
        "link": "https://wethestudy.webflow.io/learn/hyperbola-orientations",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "hyperbola",
        "name": "Hyperbola",
        "courseMapName": "Hyperbola",
        "parentId": "the-conics",
        "link": "https://wethestudy.webflow.io/learn/hyperbola",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "hyperbola-basic-geometry",
        "name": "Hyperbola: Basic Geometry",
        "courseMapName": "Basic Geometry",
        "parentId": "hyperbola",
        "link": "https://wethestudy.webflow.io/learn/hyperbola-basic-geometry",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "function-types",
        "name": "Function Types",
        "courseMapName": "Types",
        "parentId": "relations-and-functions",
        "link": "https://wethestudy.webflow.io/learn/function-types",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "extrema-optimization-problems",
        "name": "Extrema: Optimization Problems",
        "courseMapName": "Optimization Problems",
        "parentId": "extrema-of-a-function-maximum-and-minimum",
        "link": "https://wethestudy.webflow.io/learn/extrema-optimization-problems",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "extrema-of-a-function-maximum-and-minimum",
        "name": "Extrema of a Function: Maximum and Minimum",
        "courseMapName": "Extrema",
        "parentId": "differential-calculus-applications",
        "link": "https://wethestudy.webflow.io/learn/extrema-of-a-function-maximum-and-minimum",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "extrema-derivative-tests",
        "name": "Extrema: Derivative Tests",
        "courseMapName": "Derivative Tests",
        "parentId": "extrema-of-a-function-maximum-and-minimum",
        "link": "https://wethestudy.webflow.io/learn/extrema-derivative-tests",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "explicit-and-implicit-domains",
        "name": "Explicit and Implicit Domains",
        "courseMapName": "Explicit and Implicit",
        "parentId": "constructing-mathematical-functions",
        "link": "https://wethestudy.webflow.io/learn/explicit-and-implicit-domains",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "differential-equation-solutions-numerical-approach",
        "name": "Differential Equation Solutions: Numerical Approach",
        "courseMapName": "Numerical Approach",
        "parentId": "differential-equations-solutions",
        "link": "https://wethestudy.webflow.io/learn/differential-equation-solutions-numerical-approach",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "ellipse-orientations",
        "name": "Ellipse: Orientations",
        "courseMapName": "Orientations",
        "parentId": "ellipse",
        "link": "https://wethestudy.webflow.io/learn/ellipse-orientations",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "ellipse-basic-geometry",
        "name": "Ellipse: Basic Geometry",
        "courseMapName": "Basic Geometry",
        "parentId": "ellipse",
        "link": "https://wethestudy.webflow.io/learn/ellipse-basic-geometry",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "evaluating-mathematical-functions",
        "name": "Evaluating Mathematical Functions",
        "courseMapName": "Evaluation",
        "parentId": "mathematical-functions-basics",
        "link": "https://wethestudy.webflow.io/learn/evaluating-mathematical-functions",
        "order": "4",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "ellipse-area",
        "name": "Ellipse: Area",
        "courseMapName": "Area",
        "parentId": "ellipse",
        "link": "https://wethestudy.webflow.io/learn/ellipse-area",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "differential-equations-applications",
        "name": "Differential Equations: Applications",
        "courseMapName": "Applications",
        "parentId": "differential-equations",
        "link": "https://wethestudy.webflow.io/learn/differential-equations-applications",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "ellipse",
        "name": "Ellipse",
        "courseMapName": "Ellipse",
        "parentId": "the-conics",
        "link": "https://wethestudy.webflow.io/learn/ellipse",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "differential-equation-solutions-graphical-approach",
        "name": "Differential Equation Solutions: Graphical Approach",
        "courseMapName": "Graphical",
        "parentId": "differential-equations-solutions",
        "link": "https://wethestudy.webflow.io/learn/differential-equation-solutions-graphical-approach",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "differential-equation-solutions-analytical-approach",
        "name": "Differential Equation Solutions: Analytical Approach",
        "courseMapName": "Analytical",
        "parentId": "differential-equations-solutions",
        "link": "https://wethestudy.webflow.io/learn/differential-equation-solutions-analytical-approach",
        "order": "4",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "constructing-mathematical-functions",
        "name": "Constructing Mathematical Functions",
        "courseMapName": "Construction",
        "parentId": "relations-and-functions",
        "link": "https://wethestudy.webflow.io/learn/constructing-mathematical-functions",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "differential-calculus-applications",
        "name": "Differential Calculus: Applications",
        "courseMapName": "Applications",
        "parentId": "differential-calculus",
        "link": "https://wethestudy.webflow.io/learn/differential-calculus-applications",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "conic-sections-eccentricity",
        "name": "Conic Sections: Eccentricity",
        "courseMapName": "Eccentricity",
        "parentId": "conic-sections",
        "link": "https://wethestudy.webflow.io/learn/conic-sections-eccentricity",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "conic-sections",
        "name": "Conic Sections",
        "courseMapName": "Conic Sections",
        "parentId": "analytic-geometry",
        "link": "https://wethestudy.webflow.io/learn/conic-sections",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "composite-functions",
        "name": "Composite Functions",
        "courseMapName": "Composite",
        "parentId": "constructing-mathematical-functions",
        "link": "https://wethestudy.webflow.io/learn/composite-functions",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analytical-approach-separation-of-variables",
        "name": "Analytical Approach: Separation of Variables",
        "courseMapName": "Separation of Variables",
        "parentId": "differential-equation-solutions-analytical-approach",
        "link": "https://wethestudy.webflow.io/learn/analytical-approach-separation-of-variables",
        "order": "1",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analytical-numerical-and-graphical-perspectives",
        "name": "Analytical, Numerical, and Graphical Perspectives",
        "courseMapName": "Perspectives",
        "parentId": "constructing-mathematical-functions",
        "link": "https://wethestudy.webflow.io/learn/analytical-numerical-and-graphical-perspectives",
        "order": "4",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analytical-approach-first-order-linear-differential-equation",
        "name": "Analytical Approach: First Order Linear Differential Equation",
        "courseMapName": "First Order Linear",
        "parentId": "differential-equation-solutions-analytical-approach",
        "link": "https://wethestudy.webflow.io/learn/analytical-approach-first-order-linear-differential-equation",
        "order": "3",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analytical-approach-bernoulli-equation",
        "name": "Analytical Approach: Bernoulli Equation",
        "courseMapName": "Bernoulli Equation",
        "parentId": "differential-equation-solutions-analytical-approach",
        "link": "https://wethestudy.webflow.io/learn/analytical-approach-bernoulli-equation",
        "order": "4",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    },
    {
        "id": "analytical-approach-homogeneous-differential-equations",
        "name": "Analytical Approach: Homogeneous Differential Equations",
        "courseMapName": "Homogeneous",
        "parentId": "differential-equation-solutions-analytical-approach",
        "link": "https://wethestudy.webflow.io/learn/analytical-approach-homogeneous-differential-equations",
        "order": "2",
        "category": "Mathematics",
        "courseSummary": "",
        "relatedLinks": []
    }
]

export default sampleData